# Generated by Django 5.0.4 on 2024-05-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigmartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Descptn', models.CharField(max_length=250, null=True)),
                ('C_image', models.ImageField(blank=True, null=True, upload_to='C_image')),
            ],
        ),
    ]
