# Generated by Django 5.0.4 on 2024-05-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigmartdb',
            name='C_image',
            field=models.ImageField(blank=True, null=True, upload_to='Category Images'),
        ),
    ]
