# Generated by Django 5.0.5 on 2024-05-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_signindb_signupdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SigninDB',
        ),
        migrations.DeleteModel(
            name='SignupDB',
        ),
    ]
