# Generated by Django 5.0.5 on 2024-05-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_signindb_signupdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signindb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='signupdb',
            name='Email',
        ),
        migrations.AddField(
            model_name='signindb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
