# Generated by Django 5.0.5 on 2024-05-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_signindb_email_remove_signupdb_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdb',
            old_name='Password',
            new_name='Password1',
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Password2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
