# Generated by Django 5.0.5 on 2024-05-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_rename_password_signupdb_password1_signupdb_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='Password2',
        ),
    ]
