# Generated by Django 5.0.5 on 2024-05-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_remove_signupdb_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SigninDB',
        ),
        migrations.DeleteModel(
            name='SignupDB',
        ),
    ]
