# Generated by Django 5.0.5 on 2024-06-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_cartdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='Mobile',
        ),
    ]
