# Generated by Django 5.0.5 on 2024-06-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_remove_registerdb_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
