# Generated by Django 5.0.5 on 2024-06-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_cartdb_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Price',
        ),
    ]
