# Generated by Django 5.0.5 on 2024-06-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_remove_cartdb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDetailsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
