# Generated by Django 5.0.5 on 2024-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_checkoutdetailsdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
