# Generated by Django 5.0.5 on 2024-06-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_orderdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutDetailsDB',
        ),
    ]
